steps:
- task: Bash@3
  displayName: Checkout repository
  # recupere le dockerFile et le context

  # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml
- task: Docker@2
  displayName: Login container registry
  inputs:
    command: login
    containerRegistry: githubServiceConnection
    # Login fait avec un service connection fait au préalable dans l'infrastructure Azure. 
    # Le service connection contient un PAT github afin de diriger le 



- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    command: 'buildAndPush'







---
name: Create and Publish

on:
  workflow_dispatch: 

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: ##To fill##

      - name: Log in to the Container registry
        uses: ##To fill##

      - name: Build and push Docker image
        uses: ##To fill##

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: init

      - name: Log in to the Container registry 
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
